sudo docker rm -f cardb
sudo docker rm -f orddb
sudo docker rm -f usedb
sudo docker rm -f catdb
sudo docker rm -f ship
sudo docker rm -f user
sudo docker rm -f cart
sudo docker rm -f paym
sudo docker rm -f orde
sudo docker rm -f cata
sudo docker rm -f fron
sudo docker rm -f nginx
sudo docker rm -f redis